import Head from "next/head";
//import Homepage from "./portfolio";
import Reveal from "@/components/Reveal";

export default function Home() {
  return (
    <>
      <Head>
        <title>else</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Homepage /> */}
      <Reveal />
    </>
  );
}
